/* =============================================================================
 *  SEED DATA
 *  ---------------------------------------------------------------------------
 *  The real Loboratorium catalogue, used to seed the `Product` table on first
 *  run (`npm run db:seed`). After seeding, the database is the source of truth
 *  — edit products via /admin/products instead of this file.
 *  Prices, descriptions, dimensions and images are from loboratorium.be.
 * ========================================================================== */

export const seedProducts = [
  {
    id: "p1",
    slug: "dune-vaas",
    price: 7.5,
    category: "decor",
    image: "/images/dune-vaas.png",
    badge: "new",
    stock: 25,
    material: { en: "PLA", nl: "PLA", fr: "PLA" },
    dimensions: "96 × 97 × 197 mm",
    layerHeight: "0.20 mm",
    finishing: { en: "Matte", nl: "Mat", fr: "Mat" },
    name: { en: "Dune Vase", nl: "Dune Vaas", fr: "Vase Dune" },
    description: {
      en: "A modern vase with a sleek, elegant design and calm ridged lines — perfect for fresh or dried flowers, and made to blend into any interior. Choose from 24 colours.",
      nl: "Een moderne vaas met een strak, elegant ontwerp en rustige ribbels — perfect voor verse of droogbloemen en past in elk interieur. Keuze uit 24 kleuren.",
      fr: "Un vase moderne au design épuré et élégant, aux lignes douces — parfait pour fleurs fraîches ou séchées, il s'intègre à tout intérieur. 24 coloris au choix.",
    },
  },
  {
    id: "p2",
    slug: "taro-bathroom-organizer",
    price: 12.5,
    category: "desk",
    image: "/images/taro-organizer.png",
    badge: "popular",
    stock: 20,
    material: { en: "PLA", nl: "PLA", fr: "PLA" },
    dimensions: "Set · 136 × 69 × 69 mm",
    layerHeight: "0.20 mm",
    finishing: { en: "Matte", nl: "Mat", fr: "Mat" },
    name: {
      en: "Taro Bathroom Organizer",
      nl: "Taro Badkamer Organizer",
      fr: "Organiseur de salle de bain Taro",
    },
    description: {
      en: "A sleek, minimalist organizer set that keeps your bathroom tidy — toothbrush holder, cotton dispenser, tray and cup, with an open structure for ventilation and drainage. Full set.",
      nl: "Een strakke, minimalistische organizerset die je badkamer netjes houdt — tandenborstelhouder, wattenhouder, schaaltje en beker, met open structuur voor ventilatie en afvoer. Volledige set.",
      fr: "Un ensemble organiseur épuré et minimaliste pour une salle de bain bien rangée — porte-brosses, distributeur de cotons, plateau et gobelet, avec structure ouverte pour l'aération. Ensemble complet.",
    },
  },
  {
    id: "p3",
    slug: "velto-gieter",
    price: 9.99,
    category: "decor",
    image: "/images/velto-gieter.png",
    badge: null,
    stock: 0,
    material: { en: "PLA", nl: "PLA", fr: "PLA" },
    dimensions: "197 × 180 × 179 mm",
    layerHeight: "0.20 mm",
    finishing: { en: "Matte", nl: "Mat", fr: "Mat" },
    name: { en: "Velto Watering Can", nl: "Velto Gieter", fr: "Arrosoir Velto" },
    description: {
      en: "A modern watering can with a slender form and curved spout for controlled, mess-free watering — ideal for houseplants and balcony pots, indoors and out.",
      nl: "Een moderne gieter met een slanke vorm en gebogen tuit voor gecontroleerd gieten zonder gemors — ideaal voor kamerplanten en balkonpotten, binnen en buiten.",
      fr: "Un arrosoir moderne à la forme élancée et au bec courbé pour un arrosage précis et sans dégât — idéal pour plantes d'intérieur et pots de balcon.",
    },
  },
  {
    id: "p4",
    slug: "vesa-fruitschaal",
    price: 9.99,
    category: "kitchen",
    image: "/images/vesa-fruitschaal.png",
    badge: null,
    stock: 22,
    material: { en: "PLA", nl: "PLA", fr: "PLA" },
    dimensions: "229 × 233 × 73 mm",
    layerHeight: "0.20 mm",
    finishing: { en: "Matte", nl: "Mat", fr: "Mat" },
    name: { en: "Vesa Fruit Bowl", nl: "Vesa Fruitschaal", fr: "Coupe à fruits Vesa" },
    description: {
      en: "A fruit bowl with a modern, open design for good airflow — equally at home holding fruit, bread or keys. Pick two colours: one for the top, one for the base.",
      nl: "Een fruitschaal met een modern, open ontwerp voor goede ventilatie — net zo goed voor fruit, brood of sleutels. Kies twee kleuren: één voor boven, één voor onder.",
      fr: "Une coupe à fruits au design moderne et ajouré pour une bonne aération — aussi bien pour les fruits que le pain ou les clés. Choisissez deux couleurs : le haut et le bas.",
    },
  },
  {
    id: "p5",
    slug: "playbookd-four-in-a-row",
    price: 17.5,
    category: "tech",
    image: "/images/playbookd-four-in-a-row.png",
    badge: "new",
    stock: 15,
    material: { en: "PLA", nl: "PLA", fr: "PLA" },
    dimensions: "Book format",
    layerHeight: "0.20 mm",
    finishing: { en: "Matte", nl: "Mat", fr: "Mat" },
    name: {
      en: "Playbook'd — Four in a Row",
      nl: "Playbook'd — Vier op een Rij",
      fr: "Playbook'd — Puissance 4",
    },
    description: {
      en: "A modern take on Connect Four that looks like a book on your shelf — open it up and it becomes a full game board with all the pieces stored inside. Play, then tidy away.",
      nl: "Een moderne kijk op Vier op een Rij die op je boekenplank op een boek lijkt — klap 'm open en het wordt een volledig speelbord, met alle schijven netjes opgeborgen.",
      fr: "Une version moderne du Puissance 4 qui ressemble à un livre sur votre étagère — ouvrez-le et il devient un plateau de jeu complet, pions rangés à l'intérieur.",
    },
  },
  {
    id: "p6",
    slug: "vela-tissue-doos",
    price: 19.99,
    category: "decor",
    image: "/images/vela-tissue-doos.png",
    badge: null,
    stock: 18,
    material: { en: "PLA", nl: "PLA", fr: "PLA" },
    dimensions: "191 × 191 × 147 mm",
    layerHeight: "0.20 mm",
    finishing: { en: "Matte", nl: "Mat", fr: "Mat" },
    name: {
      en: "Vela Tissue Box Cover",
      nl: "Vela Tissuedoos",
      fr: "Boîte à mouchoirs Vela",
    },
    description: {
      en: "A minimalist cover for square tissue boxes that hides the packaging and fits right into a modern interior — bathroom, living room or office.",
      nl: "Een minimalistische hoes voor vierkante tissuedozen die de verpakking wegwerkt en naadloos past in een modern interieur — badkamer, woonkamer of kantoor.",
      fr: "Un cache minimaliste pour boîtes de mouchoirs carrées qui dissimule l'emballage et s'intègre à un intérieur moderne — salle de bain, salon ou bureau.",
    },
  },
];
